### ISSUE TITLE
About How to predict by tensorflow serving.

### ISSUE THREAD

**Issue by LymanLiuChina** [bendangnuksung/mrcnn_serving_ready#24] opened 2019-11-19 06:20 UTC
Hi,
   I've deployed the model to the server, but I don't know how to import data from the client. Could you help me? Thank you

**Comment by bendangnuksung** [comment] 2019-11-19 06:59
Hi! just update the code for inferencing using TensorFlow serving. Please check ReadMe.

**Comment by bendangnuksung** [comment] 2019-11-19 07:42
Closed & Duplicate of #19

**Closed by bendangnuksung** 2019-11-19 07:42 UTC
